### ISSUE TITLE
[Question] DXF Export Job

### ISSUE THREAD

**Issue by mlkuczkowski** [koechlm/Vault-Sample---STEPExportJob#1]
Hello.

I have question about using DXF Translation AddIn in Inventor Server. Based on Inventor SDK and your sample, I created function converting sheet metal file to dxf. Unfortunately file created is empty. Is DXF Translator supported in Inventor Server? And is there any other method to save sheet metal file as dxf file (its important to me to use ini file)?

Best regards
Michał Kluczkowski

**Comment by koechlm** [comment]
Hello Michal,
all translator add-ins are supported by VaultInventorServer. There has been an issue for DWG/DXF in the very first 2018.2 release of it, but all later versions should work. 
Would you mind trying my evaluation code for it? This code is not production-ready but helped to validate the DXF capability when we had to solve the issue. 

`try
                {
                    TranslatorAddIn mSATTrans = mInvSrvAddIns.ItemById["{89162634-02B6-11D5-8E80-0010B541CD80}"] as TranslatorAddIn;
                    mSATTrans.Activate();
                    TranslatorAddIn mDXFTrans = mInvSrvAddIns.ItemById["{C24E3AC4-122E-11D5-8E91-0010B541CD80}"] as TranslatorAddIn;
                    mDXFTrans.Activate();
                    if (mDXFTrans.LicenseStatus != AddInLicenseStatusEnum.kAddInLicenseStatusUnlicensed)
                    {
                        mDXFTrans.Activate();
                    }

                }
                catch (Exception ex)
                {
                    // any activation error...
                }
                Document mDoc = mInv.Documents.Open("C:\\Temp\\SampleSheetMetalPart.ipt");
                PartDocument mPartDoc = (PartDocument)mDoc;
                DataIO mDataIO = mPartDoc.ComponentDefinition.DataIO;
                String mOut = "FLAT PATTERN DXF?AcadVersion=R12&OuterProfileLayer=Outer";
                mDataIO.WriteDataToFile(mOut, "C:\\Temp\\SampleSheetMetalPartFlattened.dxf");`
[SampleSheetMetalPart.zip](https://github.com/koechlm/Vault-Sample---STEPExportJob/files/3362809/SampleSheetMetalPart.zip)

**Comment by koechlm** [comment]
I run the code in 2019 and just also in 2020 again. Worked, so there is no regression again. Let me know how it turned out for you, please.

**Comment by mlkuczkowski** [comment]
Hello Marcus,

thank You for your answer. I'm not sure if I understand that code correctly.
In the first step You activate DXF translator like that:

```
TranslatorAddIn mDXFTrans = mInvSrvAddIns.ItemById["{C24E3AC4-122E-11D5-8E91-0010B541CD80}"] as TranslatorAddIn;
mDXFTrans.Activate();
```
Then You do not use _mDXFTrans_ object but instead translate ipt to dxf using good old way by using DataIO:

```
Document mDoc = mInv.Documents.Open("C:\\Temp\\SampleSheetMetalPart.ipt");
PartDocument mPartDoc = (PartDocument)mDoc;
DataIO mDataIO = mPartDoc.ComponentDefinition.DataIO;
String mOut = "FLAT PATTERN DXF?AcadVersion=R12&OuterProfileLayer=Outer";
mDataIO.WriteDataToFile(mOut, "C:\\Temp\\SampleSheetMetalPartFlattened.dxf");
```
As far as I was concerned use of translators should use translator object, just like in STP translator:


```
var translator = (TranslatorAddIn)server.ApplicationAddIns.ItemById["{90AF7F40-0C01-11D5-8E83-0010B541CD80}"];
                
if (translator == null)
{
	throw new Exception("Translator addin is not available");
}

var context = server.TransientObjects.CreateTranslationContext();
var options = server.TransientObjects.CreateNameValueMap();
var dataMedium = server.TransientObjects.CreateDataMedium();

if (translator.HasSaveCopyAsOptions[doc, context, options])
{
	options.Value["ApplicationProtocolType"] = 2;

	var fileName = doc.FullDocumentName.Replace(extention, ".stp");

	dataMedium.FileName = fileName;
	context.Type = IOMechanismEnum.kFileBrowseIOMechanism;
	translator.SaveCopyAs(doc, context, options, dataMedium);
}
```

Could please verify once again that You meant using translator not DataIO?

**Comment by koechlm** [comment]
Hi again,
I think Flat-Pattern export is not the same as saving the document as other formats.
The translator add-in is required in any case, this for sure, as this was the objective using this code.
Thanks,
Markus
